name: Lint Docs

on:
  push:
    branches: [main]
    paths: ['**/*.md', '**/*.yml']
  pull_request:

env:
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  check-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Setup V
        uses: vlang/setup-v@v1.3

      - name: Checkout ${{ env.REPO_NAME }}
        uses: actions/checkout@v3
        with:
          path: ${{ env.REPO_NAME }}

      - name: Copy ${{ env.REPO_NAME }} to .vmodules
        run: cp -r ${{ env.REPO_NAME }} ${{ env.MOD_PATH }}

      - name: Check Markdown
        run: v check-md -hide-warnings ${{ env.REPO_NAME }}
